// data.js

const goodsData = [
    {
        productId: "SP001",
        productName: "Bánh quy",
        barCode: "1234567890123",
        category: "Thực phẩm",
        description: "Bánh quy giòn thơm, hương vị bơ đặc biệt",
        expiryDate: "2024-12-31",
        taxRate: "10%",
        location: "Kệ A1",
        entryPrice: 20000,
        salePrice: 25000,
        unit: "Hộp",
        stockQuantity: 50,
        imageUrl: "https://via.placeholder.com/400x300?text=Banh+Quy",
    },
    {
        productId: "SP002",
        productName: "Sữa tươi",
        barCode: "9876543210987",
        category: "Thực phẩm",
        description: "Sữa tươi nguyên chất, không đường",
        expiryDate: "2024-08-20",
        taxRate: "5%",
        location: "Tủ lạnh B2",
        entryPrice: 15000,
        salePrice: 18000,
        unit: "Chai",
        stockQuantity: 100,
        imageUrl: "https://via.placeholder.com/400x300?text=Sua+Tuoi",
    },
    {
        productId: "SP003",
        productName: "Nước ngọt Coca-Cola",
        barCode: "1928374650912",
        category: "Đồ uống",
        description: "Nước ngọt Coca-Cola vị truyền thống",
        expiryDate: "2025-01-01",
        taxRate: "10%",
        location: "Kệ D3",
        entryPrice: 10000,
        salePrice: 12000,
        unit: "Lon",
        stockQuantity: 200,
        imageUrl: "https://via.placeholder.com/400x300?text=Coca+Cola",
    },
    {
        productId: "SP004",
        productName: "Dầu gội Head & Shoulders",
        barCode: "5647382910123",
        category: "Mỹ phẩm",
        description: "Dầu gội chống gàu, dưỡng tóc chắc khỏe",
        expiryDate: "2025-05-15",
        taxRate: "8%",
        location: "Kệ C1",
        entryPrice: 75000,
        salePrice: 90000,
        unit: "Chai",
        stockQuantity: 80,
        imageUrl: "https://via.placeholder.com/400x300?text=Head+Shoulders",
    },
    {
        productId: "SP005",
        productName: "Kem đánh răng Colgate",
        barCode: "2938475610293",
        category: "Mỹ phẩm",
        description: "Kem đánh răng Colgate ngừa sâu răng",
        expiryDate: "2024-11-30",
        taxRate: "5%",
        location: "Kệ C2",
        entryPrice: 35000,
        salePrice: 42000,
        unit: "Tuýp",
        stockQuantity: 120,
        imageUrl: "https://via.placeholder.com/400x300?text=Colgate",
    },
];

export default goodsData;
