const productsData = [
    {
        productId: "SP001",
        productName: "Bánh quy",
        barcode: "1234567890123",
        category: "Thực phẩm",
        productDescription: "Bánh quy giòn thơm, hương vị bơ đặc biệt",
        expiryDate: "2024-12-31",
        tax: "10%",
        location: "Kệ A1",
        cost: 20000,
        price: 25000,
        unit: "Hộp",
        inventoryCount: 50,
        image: "https://via.placeholder.com/400x300?text=Banh+Quy",
        status: true,  // Cột trạng thái
    },
    {
        productId: "SP002",
        productName: "Sữa tươi",
        barcode: "9876543210987",
        category: "Thực phẩm",
        productDescription: "Sữa tươi nguyên chất, không đường",
        expiryDate: "2024-08-20",
        tax: "5%",
        location: "Tủ lạnh B2",
        cost: 15000,
        price: 18000,
        unit: "Chai",
        inventoryCount: 100,
        image: "https://via.placeholder.com/400x300?text=Sua+Tuoi",
        status: true,  // Cột trạng thái
    },
    {
        productId: "SP003",
        productName: "Nước ngọt Coca-Cola",
        barcode: "1928374650912",
        category: "Đồ uống",
        productDescription: "Nước ngọt Coca-Cola vị truyền thống",
        expiryDate: "2025-01-01",
        tax: "10%",
        location: "Kệ D3",
        cost: 10000,
        price: 12000,
        unit: "Lon",
        inventoryCount: 200,
        image: "https://via.placeholder.com/400x300?text=Coca+Cola",
        status: true,  // Cột trạng thái
    },
    {
        productId: "SP004",
        productName: "Dầu gội Head & Shoulders",
        barcode: "5647382910123",
        category: "Mỹ phẩm",
        productDescription: "Dầu gội chống gàu, dưỡng tóc chắc khỏe",
        expiryDate: "2025-05-15",
        tax: "8%",
        location: "Kệ C1",
        cost: 75000,
        price: 90000,
        unit: "Chai",
        inventoryCount: 80,
        image: "https://via.placeholder.com/400x300?text=Head+Shoulders",
        status: true,  // Cột trạng thái
    },
    {
        productId: "SP005",
        productName: "Kem đánh răng Colgate",
        barcode: "2938475610293",
        category: "Mỹ phẩm",
        productDescription: "Kem đánh răng Colgate ngừa sâu răng",
        expiryDate: "2024-11-30",
        tax: "5%",
        location: "Kệ C2",
        cost: 35000,
        price: 42000,
        unit: "Tuýp",
        inventoryCount: 120,
        image: "https://via.placeholder.com/400x300?text=Colgate",
        status: true,  // Cột trạng thái
    },
];

export default productsData;
